### ISSUE TITLE
Looks great one problem

### ISSUE THREAD

**Issue by iGetUploaded** [mezmer420/dashi#4]
So I put all the right things into the config.json and when I go to start the bot I get this giant error.. Not sure what too do

![image](https://user-images.githubusercontent.com/54633753/189050222-1d258193-4437-4418-a5e8-976e6969c81e.png)

**Comment by iamchomad** [comment]
Hey man, did you do it right? try to check the data in `config.json` again, it looks like something is missing.

**Comment by iGetUploaded** [comment]
If you mean by putting the bot token and the api token in then yeah I did?

Do I have to change anything else or just with the config

**Comment by iamchomad** [comment]
> If you mean by putting the bot token and the api token in then yeah I did?
> 
> Do I have to change anything else or just with the config

Maybe he forgot something, if it's configured properly, it won't be like that

**Comment by iGetUploaded** [comment]
It loads fine until the dashboard part 
![image](https://user-images.githubusercontent.com/54633753/189265541-ae094b0c-1271-4342-87fd-0f2b45e7c5f9.png)

any idea how to solve this or nah?

**Comment by iGetUploaded** [comment]
Did get it to load up just got some errors here and there but it does work

**Comment by mezmer420** [comment]
Sorry for the late reply, I assume you managed to figure it out. If not, feel free to bring up any issues you might still have. Also thanks for checking out this repository.

**Comment by iGetUploaded** [comment]
I have figured most of it out just getting some errors still such as:
![image](https://user-images.githubusercontent.com/54633753/191146836-699fb738-16c7-4937-836e-967c0417f637.png)

I've been getting this error on quite a few of the cmds

**Comment by mezmer420** [comment]
hmm... if you have a database.js file, and in the ready.js file it's properly syncing and passing through everything, it should work fine. If you have Discord you can shoot me a DM and I might be able to help better. (also on an unrelated note I just now updated the config.json file with stuff you need for the dashboard to work properly, I forgot all about it lol)

**Comment by iGetUploaded** [comment]
looked at both database and ready didnt seem to find anything wrong with them.. I also updated config, and I do have discord added you its poptart
